### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by ivankravets** [sipeed/platform-gd32v#1]
Firstly, thank you so much for this dev/platform! 😊 

1) A lot of tracks to Kendryte, such as -> https://github.com/sipeed/platform-gd32v/tree/master/examples/longan-nano-blink

2) `gd32vf103_firmware_library` - what is it? Is this SDK? Can we get a better name for it? If it is a library, we can omit the `framework` field in `platformio.ini` and submit this library to PlatformIO Registry. Later, developers can use it with `lib_deps = gd32vf103....`.

3) Could you remove custom `init_cmds` from board manifests for `debug` section? The default should work as well. Could you test this?

4) Can you add me to collaborators list for this repository? We would like to add this dev/platform to a public registry.

**Comment by bitsk** [comment]
Hi @ivankravets ,

I have modified these code and now ready for release.  
These are the packages required for the windows platform.
```json
 "tool-openocd-gd32v": [
    {
        "sha1": "12fb7af4027f0cd4eff53a3ab4d94f395416fe3b", 
        "system": [
          "windows_x86", 
          "windows_amd64"
        ], 
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/tool-openocd-gd32v-v0.1.1-win.tar.gz", 
        "version": "0.1.1"
    }
 ],
"toolchain-gd32v": [
	{
		"sha1": "c7858c6757c11101a0a7fa261ee525e62b29742d",
		"system": [
          "windows_x86", 
          "windows_amd64"
        ], 
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/toolchain-gd32v-v9.2.0-win.tar.gz", 
        "version": "9.2.0"
	}
],
"tool-gd32vflash": [
	{
		"sha1": "44deb6bacdf05cd12d37470b51e0236acd5506de",
		"system": [
          "windows_x86", 
          "windows_amd64"
        ], 
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/tool-gd32vflash-v0.1.0-win.tar.gz", 
        "version": "0.1.0"
	}
],
"framework-gd32vf103-sdk":[
    {
        "sha1": "27554d2e811e4bea8d2f8380a8188ec0425724fd",
        "system": "*",
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/framework-gd32vf103-sdk-v1.0.0.tar.gz",
        "version": "1.0.0"
	}
    ],
"framework-arduino-gd32v":[
     {
        "sha1": "0791bc2f745c0b7884458294c6cc1ef281896e4f",
        "system": "*",
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/framework-arduino-gd32v-demo-0.1.1.tar.gz",
        "version": "0.1.1"
     }
 ],
```


I will prepare the linux tool and send it to you later.

And I have added you to collaborators list, here is Invitation link:
https://github.com/sipeed/platform-gd32v/invitations

**Comment by bitsk** [comment]
By the way, some developers want us to provide an offline installation package. Can you provide some way to install PIO in vscode without a network? I set the PLATFORMIO_CORE_DIR directory, but it does not seem to work when the installation is initialized, or it will be installed in the systerm Users directory. what should I do?

**Comment by bitsk** [comment]
Here are the links of linux tools.
```json
    {
        "sha1": "e823ae8ee3affe8b597681c396e57a82eb25ef76",
        "system": "linux_x86_64",
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/tool-gd32vflash-v0.1.0-linux.tar.gz", 
        "version": "0.1.0"
    }

    {
        "sha1": "a0012f8cb070b18b2b0077b081532ac0057519d",
        "system": "linux_x86_64",
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/toolchain-gd32v-v9.2.0-linux.tar.gz", 
        "version": "9.2.0"
    }

    {
        "sha1": "a0a1cb649eda649250139290f6ca38a605efc172", 
        "system": "linux_x86_64", 
        "url": "http://dl.sipeed.com/LONGAN/platformio/dl-packages/tool-openocd-gd32v-v0.1.1-linux.tar.gz", 
        "version": "0.1.1"
    }, 


```

**Comment by ivankravets** [comment]
https://travis-ci.org/sipeed/platform-gd32v/jobs/584158170

Is this toolchain valid `http://dl.sipeed.com/LONGAN/platformio/dl-packages/toolchain-gd32v-v9.2.0-linux.tar.gz`?

**Comment by ivankravets** [comment]
Sorry, it seems like our issue with packaging. We will redeploy the new package.

**Comment by ivankravets** [comment]
The release is out! https://twitter.com/PlatformIO_Org/status/1172507702184034304

> By the way, some developers want us to provide an offline installation package.

It's possible in theory. We have a feature request for this. PlatformIO IDE installs PIO Core in virtual environment which depends on system Python.
