### ISSUE TITLE
OpenOCD source for gd32v

### ISSUE THREAD

**Issue by ChristianRinn** [sipeed/platform-gd32v#2]
Since PlatformIO uses OpenOCD under the hood and downloads the binaries from http://dl.sipeed.com/LONGAN/platformio/dl-packages/ I wonder were the source code for these binaries is. Since OpenOCD is licensed under the GPL I would appreciate if Sipeed or Gigadevices released the source code for OpenOCD or - even better - merge it with the riscv-openocd repo.

**Comment by kprasadvnsi** [comment]
I believe they used OpenOCD from this repo.

https://github.com/riscv-mcu/riscv-openocd

**Comment by ChristianRinn** [comment]
Indeed that looks good. Thanks you for the hint.
