### ISSUE TITLE
tool-dfuutil not auto-installed

### ISSUE THREAD

**Issue by maxgerhardt** [sipeed/platform-gd32v#28]
There's a report of getting a 

```
sh: 1: bin/dfu-suffix: not found
```
message during upload, which is because the `~/.platformio/packages/tool-dfuutil` package was never installed: [report](https://community.platformio.org/t/dfu-suffix-not-found-for-longan-nano-build/16710). That could only be manually fixed by downloading the package from [the bintray](https://bintray.com/platformio/tool-packages/). 

I think the platform is missing some code to mark `tool-dfuutil` package as required / not optional when using `upload_protocol = dfu`? As in 

https://github.com/platformio/platform-ststm32/blob/a05ae97d25336fd20f8774a01590b0c91d498518/platform.py#L43-L44

**Comment by ivankravets** [comment]
How is it possible if there is package dependency? https://github.com/sipeed/platform-gd32v/blob/master/platform.json#L72

**Comment by maxgerhardt** [comment]
This is a 100% reproducable though on Ubuntu 20 for me though. 

```
rm -rf ~/.platformio/packages/tool-dfuutil/
git clone https://github.com/sipeed/platform-gd32v.git
cd platform-gd32v/examples/longan-nano-blink/
echo "upload_protocol = dfu" >> platformio.ini
pio run
```
gives

```
Processing sipeed-longan-nano (platform: gd32v; framework: gd32vf103-sdk; board: sipeed-longan-nano)
--------------------------------------------------------------------------------
Platform Manager: Installing gd32v
Platform Manager: gd32v @ 1.2.0 has been installed!
Tool Manager: Installing framework-gd32vf103-sdk @ ~1.0.0
Tool Manager: framework-gd32vf103-sdk @ 1.0.0 has been installed!
Tool Manager: Installing toolchain-gd32v @ ~9.2.0
Unpacking  [####################################]  100%          08
Tool Manager: toolchain-gd32v @ 9.2.0 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/gd32v/sipeed-longan-nano.html
PLATFORM: GigaDevice GD32V (1.2.0) > Sipeed Longan Nano
HARDWARE: GD32VF103CBT6 108MHz, 32KB RAM, 128KB Flash
DEBUG: Current (altera-usb-blaster) External (altera-usb-blaster, gd-link, jlink, rv-link, sipeed-rv-debugger, um232h)
PACKAGES: 
 - framework-gd32vf103-sdk 1.0.0 
 - toolchain-gd32v 9.2.0
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
..
Checking size .pio/build/sipeed-longan-nano/firmware.elf
Adding dfu suffix to firmware.bin
sh: 1: bin/dfu-suffix: not found
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]   7.0% (used 2310 bytes from 32768 bytes)
Flash: [=         ]   5.0% (used 6572 bytes from 131072 bytes)
*** [.pio/build/sipeed-longan-nano/firmware.bin] Error 127
```

Here the *build process* uses `tool-dfuutil`. See 

https://github.com/sipeed/platform-gd32v/blob/d312b942d78d80bd9f200c7495733a04a15f366c/builder/main.py#L151-L161

But the installation of that is only triggered for me when I do a `pio run -t upload`: 

```
$ pio run -t upload 
Processing sipeed-longan-nano (platform: gd32v; framework: gd32vf103-sdk; board: sipeed-longan-nano)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing tool-gd32vflash @ ~0.1.0
Tool Manager: tool-gd32vflash @ 0.1.0 has been installed!
Tool Manager: Installing tool-dfuutil @ ~1.9.200310
Tool Manager: tool-dfuutil @ 1.9.200310 has been installed!
```
so there's just a problem *when* this package is installed, I think.

**Comment by Code7R** [comment]
No idea how this is possible but this is also reproducible on one of the Debian Unstable systems here. One works, another does not, getting this "tool-dfuutil not found" bug.

**Comment by jershell** [comment]
ubuntu 20.04 (long time support) i have the same error. 
How to reproduce
1. Install ubuntu 20.04.1 from iso by usb flash
2. install platformIO on vscode
3. create new project and try to build
...error
```
Adding dfu suffix to firmware.bin
sh: 1: bin/dfu-suffix: not found
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]   7.3% (used 2380 bytes from 32768 bytes)
Flash: [=         ]  10.9% (used 14294 bytes from 131072 bytes)
*** [.pio/build/sipeed-longan-nano/firmware.bin] Error 127
```
update: After upload, I look on try upload without build firmware and installation missing packages.  I think this action should be before the build.

**Comment by racerxdl** [comment]
Same problem here with ubuntu 20.04 but `pio run -t upload ` worked.

**Comment by ivankravets** [comment]
Resolved in https://github.com/sipeed/platform-gd32v/releases/tag/v1.2.1
