### ISSUE TITLE
Add gd32v to udev rules.

### ISSUE THREAD

**Issue by bitsk** [sipeed/platform-gd32v#8]
Hi, @ivankravets 
Can you add longan boards into https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules?
The hwids: 
                "0x28e9"
                "0x0189"
Thank you.

**Comment by ivankravets** [comment]
It seems like @adlerweb provided pull request https://github.com/platformio/platformio-core/commit/94f8afec38fc8d35db1055368f5fbe4e67c89e7e
